### ISSUE TITLE
Is it possible to use battenberg on mouse data?

### ISSUE THREAD

**Issue by evelinag** [cancerit/cgpBattenberg#31]
Hello,
I see that `battenberg.pl` takes species as an optional input parameter. What files should I give to the `-impute-info` and `-thousand-genomes-loc` parameters if the species is not set to human? 

Thank you

**Comment by sdentro** [comment]
Hi,

It is in theory possible to extend the cgpBattenberg pipeline to other 
species. If the species has a diploid genome with heterozygous germline 
SNPs it can work. We have however never attempted this. cgpBattenberg 
takes species as an input parameter strictly because our pipeline system 
requires it.

For cgpBattenberg to work on mouse data one needs that data to come from 
a mouse that has not been inbred. And it needs a haplotype reference 
panel similar to the 1000 Genomes panel that is available for human that 
is relevant to the mouse in question. At the moment I'm afraid there are 
no plans to extend the current set of reference files to other species.

Best wishes,
Stefan

On 18/05/2016 13:51, Evelina Gabasova wrote:
>
> Hello,
> I see that |battenberg.pl| takes species as an optional input 
> parameter. What files should I give to the |-impute-info| and 
> |-thousand-genomes-loc| parameters if the species is not set to human?
>
> Thank you
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/cancerit/cgpBattenberg/issues/31>
>




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by keiranmraine** [comment]
Expanding on this, we have managed to successfully generate a mouse (37 + 38) SNP panel for ASCAT using the Mouse Genomes Project data.  The tools used may be useful if you would like to investigate yourself:

https://github.com/cancerit/ascatNgs/wiki/Building-ascatNgs-reference-files-from-SNP-VCF-files

As indicated by Stefan a prerequisite is that the data is from back-crossed samples.
