### ISSUE TITLE
number of loci file error

### ISSUE THREAD

**Issue by xtmgah** [cancerit/cgpBattenberg#84]
Hello, I running cgpBattenberg (Version: 3.3.0) with the following command and then I got a error information. Can you help me to fix this issue? thanks. 

battenberg.pl -outdir IGC-02-1016-T01 -tumbam /BAM/GT01062_2018.bam  -normbam /BAM/GT01062_2017.bam -reference /ref
erence/genome.fa.fai -gender XY -impute-info /reference/impute/impute_info.txt -thousand-genomes-loc /reference/1000genomesloci -gc-correction-loc /reference/battenberg_
wgs_gc_correction_1000g_v3 -ignore-contigs-file /reference/ignore_contigs.txt ‐species Human ‐assembly GRCh37d5 -threads 8

Here is the error information:

"**The number of loci files created 24 is not the same as the number requested 1**"

**Comment by kathryn-beal** [comment]
Hi,
Could you tell me the contents of the reference/genome.fa.fai and ignore_contigs files?
Regards
Kathryn

**Comment by xtmgah** [comment]
Here are the contents:

genome.fa.fai:
1	249250621	52	80	81
2	243199373	252366358	80	81
3	198022430	498605776	80	81
4	191154276	699103539	80	81
5	180915260	892647296	80	81
6	171115067	1075824049	80	81
7	159138663	1249078107	80	81
8	146364022	1410206056	80	81
9	141213431	1558399681	80	81
10	135534747	1701378334	80	81
11	135006516	1838607320	80	81
12	133851895	1975301472	80	81
13	115169878	2110826570	80	81
14	107349540	2227436126	80	81
15	102531392	2336127590	80	81
16	90354753	2439940678	80	81
17	81195210	2531424919	80	81
18	78077248	2613635123	80	81
19	59128983	2692688390	80	81
20	63025520	2752556539	80	81
21	48129895	2816369931	80	81
22	51304566	2865101503	80	81
X	155270560	2917047429	80	81
Y	59373566	3074258928	80	81
MT	16569	3134374742	80	81
GL000207.1	4262	3134391580	80	81
GL000226.1	15008	3134395958	80	81
GL000229.1	19913	3134411216	80	81
GL000231.1	27386	3134431440	80	81
GL000210.1	27682	3134459231	80	81
GL000239.1	33824	3134487322	80	81
GL000235.1	34474	3134521631	80	81
GL000201.1	36148	3134556598	80	81
GL000247.1	36422	3134593260	80	81
GL000245.1	36651	3134630200	80	81
GL000197.1	37175	3134667372	80	81
GL000203.1	37498	3134705074	80	81
GL000246.1	38154	3134743103	80	81
GL000249.1	38502	3134781796	80	81
GL000196.1	38914	3134820842	80	81
GL000248.1	39786	3134860305	80	81
GL000244.1	39929	3134900651	80	81
GL000238.1	39939	3134941142	80	81
GL000202.1	40103	3134981643	80	81
GL000234.1	40531	3135022310	80	81
GL000232.1	40652	3135063410	80	81
GL000206.1	41001	3135104633	80	81
GL000240.1	41933	3135146209	80	81
GL000236.1	41934	3135188729	80	81
GL000241.1	42152	3135231250	80	81
GL000243.1	43341	3135273991	80	81
GL000242.1	43523	3135317936	80	81
GL000230.1	43691	3135362066	80	81
GL000237.1	45867	3135406366	80	81
GL000233.1	45941	3135452869	80	81
GL000204.1	81310	3135499447	80	81
GL000198.1	90085	3135581836	80	81
GL000208.1	92689	3135673110	80	81
GL000191.1	106433	3135767021	80	81
GL000227.1	128374	3135874848	80	81
GL000228.1	129120	3136004890	80	81
GL000214.1	137718	3136135687	80	81
GL000221.1	155397	3136275190	80	81
GL000209.1	159169	3136432593	80	81
GL000218.1	161147	3136593815	80	81
GL000220.1	161802	3136757040	80	81
GL000213.1	164239	3136920928	80	81
GL000211.1	166566	3137087283	80	81
GL000199.1	169874	3137255995	80	81
GL000217.1	172149	3137428056	80	81
GL000216.1	172294	3137602420	80	81
GL000215.1	172545	3137776931	80	81
GL000205.1	174588	3137951696	80	81
GL000219.1	179198	3138128530	80	81
GL000224.1	179693	3138310031	80	81
GL000223.1	180455	3138492034	80	81
GL000195.1	182896	3138674808	80	81
GL000212.1	186858	3138860054	80	81
GL000222.1	186861	3139049311	80	81
GL000200.1	187035	3139238571	80	81
GL000193.1	189789	3139428007	80	81
GL000194.1	191469	3139620232	80	81
GL000225.1	211173	3139814158	80	81
GL000192.1	547496	3140028034	80	81
NC_007605	171823	3140582410	80	81



ignore_contigs.txt:

Y
MT
GL000207.1
GL000226.1
GL000229.1
GL000231.1
GL000210.1
GL000239.1
GL000235.1
GL000201.1
GL000247.1
GL000245.1
GL000197.1
GL000203.1
GL000246.1
GL000249.1
GL000196.1
GL000248.1
GL000244.1
GL000238.1
GL000202.1
GL000234.1
GL000232.1
GL000206.1
GL000240.1
GL000236.1
GL000241.1
GL000243.1
GL000242.1
GL000230.1
GL000237.1
GL000233.1
GL000204.1
GL000198.1
GL000208.1
GL000191.1
GL000227.1
GL000228.1
GL000214.1
GL000221.1
GL000209.1
GL000218.1
GL000220.1
GL000213.1
GL000211.1
GL000199.1
GL000217.1
GL000216.1
GL000215.1
GL000205.1
GL000219.1
GL000224.1
GL000223.1
GL000195.1
GL000212.1
GL000222.1
GL000200.1
GL000193.1
GL000194.1
GL000225.1
GL000192.1
NC_007605
hs37d5

**Comment by kathryn-beal** [comment]
Hi,
The number of requested loci is the loci in the genome.fa.fai file minus the loci in the ignore_contigs file so to get 1 would mean that the two files only differ by one contig name - which doesn't agree with the contents of the files you sent. It seems even more odd that this randomly sometimes works and sometimes doesn't. Are you running the command on different machines? Could you send the command when it doesn't work and when it does work, just in case there is a subtle difference?
Regards
Kathryn

**Comment by xtmgah** [comment]
Hello, Here is one example command I used to run. Yes, I submit the same command to different computers and some works, some doesn't. I believe there are some subtle difference. I try many times and have to repeat the same command to make the program run correctly. 


battenberg.pl -outdir IGC-02-1016-T01 -tumbam /BAM/GT01062_2018.bam -normbam /BAM/GT01062_2017.bam -reference /ref
erence/genome.fa.fai -gender XY -impute-info /reference/impute/impute_info.txt -thousand-genomes-loc /reference/1000genomesloci -gc-correction-loc /reference/battenberg_
wgs_gc_correction_1000g_v3 -ignore-contigs-file /reference/ignore_contigs.txt ‐species Human ‐assembly GRCh37d5 -threads 8

**Comment by TakaYamaguchi** [comment]
Hi,

I've got the same issue as well and it's not reproducible (Just removing the tmp dir and rerunning will work). Any updates on this?

Thanks,

Taka

**Comment by kathryn-beal** [comment]
Hi,
I am unable to reproduce this problem. We have run battenberg in our pipeline many thousands of times and have never seen this issue. Were any files are created in the tmpBattenberg directory? Are you using threads? Have you tried without threads?
Sorry I can't be of more help.
Kathryn

**Comment by TakaYamaguchi** [comment]
Both with or without threads had this issue. For some reason, the step created 47 loci files instead of 23 loci files. Each chr gets two or three loci files but some of them were duplicated. For example, two loci files were generated for chr10 
1000genomesloci2012_chr10_split10.txt 1000genomesloci2012_chr10_split20.txt but they were the same files.

**Comment by TakaYamaguchi** [comment]
(please ignore the previous message - deleted) Both with or without threads had this issue. For some reason, the step created 24 loci files instead of 23 loci files. For example, two files were generated for chr2 like 1000genomesloci2012_chr2_split10.txt 1000genomesloci2012_chr2_split11.txt. 

tail of the split10.txt
2       121456648
2       121456650
2       121456783
2       121456859
2       121456861
2       121457260
2       121457309
2       121457383
2       121457611
2       121457616

head of the split11.txt 
2       121457783
2       121457785
2       121457815
2       121457854
2       121457921
2       121457956
2       121457964
2       121457965
2       121458193
2       121458293

wc -l gave both 1587650 (probably just split the original loci file into 2)

1587650 1000genomesloci2012_chr2_split10.txt
 1587650 1000genomesloci2012_chr2_split11.txt

**Comment by kathryn-beal** [comment]
The default behavior is to create as many split files as there are requested contigs (genome.fa.fai file - ignore_contigs file). You should always get at least 23 split files (the number of 1000genome loci files) although you can request more by using the num_loci_files flag which allows for parallelisation of the allelecount step. In your case, it has asked for 24 files which is why chr2 has been split.
The problem seems to be in finding the number of requested contigs ie parsing the fai and ignore_contigs files. If you are using the same files as the previous post, there should be 23 chromosomes. Could you check for any 'hidden' characters in those files which may be confusing things eg by running od -cb genome.fa.fai? Are you running on different machines - is it consistently breaking on a particular type of machine? Could the perl version be different?
Kathryn

**Comment by TakaYamaguchi** [comment]
The Perl version should be the same and each node should have the same configuration. There's no hidden characters in the fai file. I'll try the num_loci_files option to fix the number from the command line.

**Comment by TakaYamaguchi** [comment]
Hi, just to let you know that I still encountered the same issue although the 'num_loci_files' option was used.

**Comment by TakaYamaguchi** [comment]
Hi, I looked into the code and the randomness was due to not sorting the keys of %$loci_per_file. at https://github.com/cancerit/cgpBattenberg/blame/dev/perl/lib/Sanger/CGP/Battenberg/Implement.pm#L243

As $num_loci_per_split is adjusted for each file at https://github.com/cancerit/cgpBattenberg/blame/dev/perl/lib/Sanger/CGP/Battenberg/Implement.pm#L268, $number_of_split_files_for_chr = int($loci_per_file->{$file} / $num_loci_per_split); can be 2 (It's rare but still happens), which will trigger  die("The number of loci files created $total_number_of_split_files_created is not the same as the number requested $num_loci_files\n") 

For example,
1000genomesloci2012_chr2.txt
3175300 1531514.72727273 ($loci_per_file->{$file} / $num_loci_per_split)

It seems that adding sort (i.e. sort keys %$loci_per_file) to the line L243 fixed the issue in my case.

**Comment by TakaYamaguchi** [comment]
Also, I think the die comment should be
die("The number of loci files created $total_number_of_split_files_created is not the same as the number requested **$requested_num_loci_files**\n");
instead of 
die("The number of loci files created $total_number_of_split_files_created is not the same as the number requested $num_loci_files\n"); ?

**Comment by kathryn-beal** [comment]
Thank you for taking the time to look into this. We had also suspected the hash order to be the problem and we were not seeing the same randomness as we run on perl 5.16.3. 
I hope to have a hotfix version out early next week.

**Comment by TakaYamaguchi** [comment]
No problem. I didn't know that the order used to be constant. It seems that they changed it from Perl 5.18.

https://www.perlmonks.org/?node_id=1005122

Thanks,

Taka

**Comment by kathryn-beal** [comment]
I've just made a 3.3.1 release. Could you let me know if this has fixed the issue?
Kathryn

**Comment by xtmgah** [comment]
@kathryn-beal Thanks for fixing this. Can you also update the Battenberg in the docker version : dockstore-cgpwgs .

**Comment by kathryn-beal** [comment]
Unfortunately battenberg is no longer in the dockstore-cgpwgs as of version 2.1.0
https://github.com/cancerit/dockstore-cgpwgs/blob/master/CHANGES.md
Kathryn
